### PR TITLE
Add upside down orientation to enable Slide Over & Split View.

### PR DESCRIPTION
**Pull request by cbpowell**
Adds the one missing orientation (all 4 are required) to enable Slide Over & Split View on the iPad.

### CODE REVIEW

**Comment by c99koder** [comment]
Upside down orientation is already enabled for iPads and slide over and split view are already working. This patch only enables it for phones.

**Comment by cbpowell** [comment]
Ah, odd - it was non-functional on my iPad Pro (9.7"), but adding that fourth orientation fixed it. The [docs do state](https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/AdoptingMultitaskingOniPad/QuickStartForSlideOverAndSplitView.html#//apple_ref/doc/uid/TP40015145-CH13-SW1) that all four are required for support on iPad.

**Comment by c99koder** [comment]
The key below the one you modified contains the iPad-specific orientations, and all 4 are supported.

**Comment by cbpowell** [comment]
Missed that before! I'll do some more testing - but I can confirm the current store version of IRCCloud does _not_ work with my iPad Pro 9.7" and Slide Over/Split Screen. If ircc is the main app and a slide over app is opened, I can't resize to get split screen. I also don't get ircc in the list of slide over apps when working in a different (split screen capable) primary application.

**Comment by c99koder** [comment]
We haven't submitted the update with slide over to the App Store yet

**Comment by cbpowell** [comment]
That would explain it…guess that's what I get for not building the fresh code first. Sorry!

**Comment by c99koder** [comment]
You can register your device for beta testing through Crashlytics here if you don't want to compile the app yourself: https://betas.to/f43ZRbMf

**Comment by cbpowell** [comment]
Thanks - I actually do run the betas on my phone, but hadn't thought to install it on my (new) iPad.

**Pull request closed without merging**
